### ISSUE TITLE
[Navigation] Navigating with PopUpto inclusive causing AnimatedNavHost enter animation to be different than specified

### ISSUE THREAD

**Issue by csabii** [google/accompanist#1006]
### **Description**
Compose: 1.1.0
Accompanist version: 0.23.0
(Happens with 1.2.0-alpha versions with 0.24.x Accompanist as well

Hi,

When navigating from screen A to screen B, with popUpTo + inclusive true even if we have enter animation set to AnimatedNavHost, some other, sliding from top left animation is used instead.
```
navController.navigate(route = Screen.Second.route) {
    popUpTo(route = Screen.First.route) { inclusive = true }
}
```
If we don't use  '{ inclusive = true }' , it is fine.

Also, navigation must happen inside Scaffold, to be able to reproduce.

### **Steps to reproduce**
Check attached small sample,
1. run the app in emulator paying attention to animation at start. Might need a restart to catch it.
2. to check control animation: simply remove { inclusive = true } or change scaffold to surface for example

### **Expected behavior** 
the animation passed to AnimatednNavHost should be used instead of top left slide in animation or whatever it is :)

**Additional context**
[nav_enteranimbug_w_scaffold.zip](https://github.com/google/accompanist/files/8042162/nav_enteranimbug_w_scaffold.zip)

**Comment by csabii** [comment]
The behavior is also observable when we add a nav graph to the AnimationNavHost and set the startDestination to that other route. Initial enteranim is skipped in that case as well (at least there is no flicker, just a default fadein, it seems). This might be one and the same stuff.

Attached an other small sample. Just check Navigation.kt, I have tried and set enteranim to each level (just to see if it is a level specific issue), but the problem is not there.

Thanks
[enteranimbug_alt.zip](https://github.com/google/accompanist/files/8051298/enteranimbug_alt.zip)

**Comment by jbw0033** [comment]
I'm not sure what animation you are seeing. I slowed down the fades in the first app and it just does a slow fade in.

You're attempting to pop your start destination off of the Navigation back stack which goes against the [Principles of Navigation](https://developer.android.com/guide/navigation/navigation-principles) that still apply in Compose.

So any slide animation you see would have to be coming from outside of Navigation since it would be like you going from no screen to `Screen.Second.route` instead of from `Screen.First.route` to `Screen.Second.route`. 

We have some guidance for conditional navigation [here](https://developer.android.com/guide/navigation/navigation-conditional) and although it is implemented with fragments, the concepts still apply in compose.
