### ISSUE TITLE
[Swipe to refresh] Can we trigger `onRefresh` for the first `true` state?

### ISSUE THREAD

**Issue by Goooler** [google/accompanist#1093]
**Description**
I want to trigger `onRefresh` for the first `true` state so that I can initialize data from the network, but seems it doesn't work, just showing the loading on UI but no callback.

**Steps to reproduce**
```kotlin
  setContent {
    val isRefreshing by vm.isRefreshing.observeAsState(true)
    MaterialTheme {
      SwipeRefresh(state = rememberSwipeRefreshState(isRefreshing), onRefresh = {}) {
        Column(
          modifier = Modifier
            .padding(8.dp)
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
        ) {
          // ...
        }
      }
    }
  }
```
More details see https://github.com/Goooler/DemoApp/pull/61.

**Expected behavior** 
Can trigger `onRefresh` for the first time.

**Additional context**
AGP: 7.1.2
Compose: 1.1.1
Accompanist: 0.23.1

**Comment by bentrengrove** [comment]
No you can't because that's not really a good way to structure Compose code. Compose just shows the current state.

There are many ways to achieve what you are trying to do though, one of the most common is just to add an init method to your viewmodel. If you need a data id or something you could add a `setup(id: String)` function to your viewmodel and call it.
