### ISSUE TITLE
HorizontalPager behaving like a Row on fast scroll

### ISSUE THREAD

**Issue by husaynchachuliya** [google/accompanist#1118]
Jetpack Compose version: 1.2.0-alpha06
Accompanist Pager: 0.24.5-alpha
Android Studio Build:
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.vecheslav.darculaDarkerTheme (1.2.0), org.sonarlint.idea (6.5.1.43866), wu.seal.tool.jsontokotlin (3.7.2), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), com.thelumiereguy.compose_helper (2.0.2)
Kotlin version: 1.6.10

Steps to Reproduce or Code Sample to Reproduce:
1. Add a HorizontalPager (infinite / large number of items) to the view.
2. Scroll fast on Pager items (fling operation)
3. Observe that randomly the pager scrolls like a Row; instead of scrolling only to the next item, scrolls continuously as Row would scroll.

Please find the sample code and screen-recording attached.
[PagerDemo.zip](https://github.com/google/accompanist/files/8407060/PagerDemo.zip)
[Screen Record](https://www.jiocloud.com/share/?s=vdC0EUwfmxLLLeeHV6uqyAX2cUf1kamSSZBAI0NkYe48BX)

**Comment by andkulikov** [comment]
Thanks for providing the demo app and the video. Unfortunately I can't reproduce it. I tried on 3 devices, was swiping with different velocity, positions, etc. Maybe you have any ideas on how to make it to reproduce?

**Comment by bentrengrove** [comment]
From the meeting with MyJio. They have reproduced it on Android 8. It works on Android 11. Was one of your devices Android 8?

**Comment by husaynchachuliya** [comment]
I checked it again on **Android 12**, and am able to reproduce the same issue. 
I swiped the pager items very fast; after some attempts, it starts behaving like a Row instead of a Pager.

**Comment by K1rakishou** [comment]
I have the same issue and I noticed that it happens almost constantly if there are microfreezes on the UI thread during the fling gesture. It's like the  In other words, if the pages have a complex and expensive content (for example very large bitmaps 5000x5000+, even if they are loaded/decoded on a background thread it still happens). It feels like ConsumeFlingNestedScrollConnection.onPostFling() is not called so the fling is not consumed and it just continues the fling until it finally stops and then it scrolls back to the page where it was supposed to stop.

**Comment by chippmann** [comment]
I did some investigating as I was affected by this behaviour as well.
The issue lies in the [snapper](https://github.com/chrisbanes/snapper) library used.

While executing `performDecayFling` it checks via `performSnapBackIfNeeded` if the target page index is reached and if so, by how much the page should scroll back to snap into place.
The problem is that said function checks the current visible page index with the target index for equality:
```kotlin
private fun calculateSnapBack(
    initialVelocity: Float,
    currentItem: SnapperLayoutItemInfo,
    targetIndex: Int,
): Int = when {
    // forwards
    initialVelocity > 0 && currentItem.index == targetIndex -> { // <- here
        layoutInfo.distanceToIndexSnap(currentItem.index)
    }
    initialVelocity < 0 && currentItem.index == targetIndex - 1 -> { // <- and here
        layoutInfo.distanceToIndexSnap(currentItem.index + 1)
    }
    else -> 0
}
```

But if a fling with a very large velocity happens and the layout is expensive to draw, the underlying `LazyList` does not always report all visible pages as visible as they are not drawn yet (i think). So in the end the `visibleItems` property does not report that a page is visible and it gets "skipped".

Hence the above `performSnapBackIfNeeded` function's if block does not register that the target page was reached if it's one of the items that got skipped.

I built the library and placed a log there:
```
Performing decay fling. vel:36449.375, current item: SnapperLayoutItemInfo(index=0, offset=-840, size=1080), target: 1
Tick | currentItem: SnapperLayoutItemInfo(index=0, offset=-841, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=2, offset=-283, size=1080) // <- as you can see, index 1 (which is the target index in this case) was skipped
Tick | currentItem: SnapperLayoutItemInfo(index=8, offset=-548, size=1080) // <- bunch of more skipps
Tick | currentItem: SnapperLayoutItemInfo(index=10, offset=-675, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=12, offset=-330, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=13, offset=-664, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=14, offset=-991, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=16, offset=-842, size=1080) // a skip again
Tick | currentItem: SnapperLayoutItemInfo(index=18, offset=-263, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=19, offset=-724, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=20, offset=-809, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=21, offset=-876, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=23, offset=-58, size=1080)
Tick | currentItem: SnapperLayoutItemInfo(index=25, offset=-664, size=1080)

// and so on until there is no velocity anymore ....
```

Changing the function like below seems to resolve this issue:
```kotlin
private fun calculateSnapBack(
    initialVelocity: Float,
    currentItem: SnapperLayoutItemInfo,
    targetIndex: Int,
): Int = when {
    // forwards
    initialVelocity > 0 && currentItem.index >= targetIndex -> { // <- change from == to >=
        layoutInfo.distanceToIndexSnap(currentItem.index)
    }
    initialVelocity < 0 && currentItem.index <= targetIndex - 1 -> { // <- change from == to <=
        layoutInfo.distanceToIndexSnap(currentItem.index + 1)
    }
    else -> 0
}
```

This will result in always reaching the correct target index, but can lead to some big "snap backs". Like if you scroll to the end of a list on Android 12 with a high velocity. But IMO this would be the expected behaviour.

All of that said; I'm not sure if this fix breaks any other functionality.
@chrisbanes I could create a PR in [snapper](https://github.com/chrisbanes/snapper) if you want and don't see any other issue with this.

**Comment by chrisbanes** [comment]
> @chrisbanes I could create a PR in [snapper](https://github.com/chrisbanes/snapper) if you want and don't see any other issue with this.

Yeah please do!

**Comment by chippmann** [comment]
> > @chrisbanes I could create a PR in [snapper](https://github.com/chrisbanes/snapper) if you want and don't see any other issue with this.
> 
> Yeah please do!

Done.
