### ISSUE TITLE
[Permissions] "Ask every time" doesn't trigger a state change

### ISSUE THREAD

**Issue by pvegh** [google/accompanist#1207]
Using something like this:

val cameraPermissionState = rememberPermissionState(Manifest.permission.CAMERA)

LaunchedEffect(cameraPermissionState.status) {
    cameraPermissionState.launchPermissionRequest()
}
if (cameraPermissionState.status.isGranted) {
} else {
}

works when the user chooses something from the dialog. Those result in state changes and the new state is represented correctly. Also if the user does then go to the settings and either denies or grants the permission, then returns to the app, also everything works with the new state value.

But when in the settings "ask every time" is chosen, and the app is brought to the foreground, the remembered state is not triggered at all. 

What am I missing? Could be a bug since everything else seems to work correctly :)

**Comment by pvegh** [comment]
Hm, no response, but it should be autoclosed now? Not much has changed in the Android world in the last 10 years :)

**Comment by pvegh** [comment]
LOL autoclosed because nobody from the team bothered to answer :)

**Comment by ForceGT** [comment]
@manuelvicnt @pvegh Do we have any update on this?

**Comment by manuelvicnt** [comment]
The `onPermissionResult: (Boolean) -> Unit = {}` callback in `Permission(s)State` should be triggered every time that the user interacts with the dialog. Would that work?

**Comment by manuelvicnt** [comment]
In which version are you seeing this behavior? I wouldn't worry too much because the behavior can vary across different Android API versions, it depends on what the platform permissions API retrieve, nothing we can control in this Accompanist wrapper.

In some OS version, they introduced the behavior that even if you say "Ask every time", they cache the user selection for some time and then it resets. So it's normal to see that even if you force close the app and open it again, the system is caching the result for you. If you force close and open it after... let's say 5 or 10 minutes, you should see the permission being requested again.

I've been testing this in API 31 and that's the behavior I saw as well

**Comment by ForceGT** [comment]
https://developer.android.com/guide/components/activities/tasks-and-back-stack#back-press-behavior

@manuelvicnt Thanks for the quick response, here's something I found regarding what you and me are facing,
The permissions won't be reset unless the process restarts

**Comment by alexvanyo** [comment]
If this is helpful, in my experience after clicking "ask every time" the permissions can be revoked while the app is in the background, even if the app isn't directly force closed by the user. So this behavior is possible:

- Grant permission with "ask every time"
- Background the app
- Wait a period of time (30 minutes is probably plenty, I don't know exact time)
- Return to the app

Because the permission was revoked, this will kill the process in a similar manner to process death.

**Comment by m120786** [comment]
I've actually had a chance to compare this behaviour with a deprecated fragment function 
```
public final void requestPermissions(     @NonNull String[] permissions,
    int requestCode )
```
What I've found is that if you set "Ask every time" in app settings, the fragment would show the dialog, however with accompanist, it just gives us `statusDenied(shouldShowRationale=false)` and it would not show the dialog.
While at the same time, if you enter the app for the first time after install or if permission is denied by default, and choose "ask every time" from the dialog, it would behave correctly in both cases (well, it doesn't show dialog every time with accompanist library, but at least treats permission as granted)

**Comment by tibomertz** [comment]
This is still an issue years later.
Using the old non compose/accompanist permission system, I can be told straight away if the user goes into the settings and changes the permission to "Ask every time".
Accompanist on the other hand remains stuck on the permission being denied.
That is, if a user denied the permission initially, then goes into the settings and picks "Ask Every Time".
Currently we can not know that the permission should be asked again, as it comes up as denied with rational to false, which is already our only signal for "denied permanently", which isn't true here.
How can we solve this?

**Comment by katajona** [comment]
Is there any update on this?
When I deny the rationale, so that it is not shown anymore and navigate to the settings while leaving the app in the background and change it to "Ask every time" and return to the app the `Denied(shouldShowRationale=false)` while the `shouldShowRationale` should be true in this case

**Comment by katajona** [comment]
For everyone wondering if you the following when arriving to te screen then the permisson dialog should pop up at the right time:
```
    val cameraPermissionState = rememberPermissionState(Manifest.permission.CAMERA)
    LifecycleStartEffect(cameraPermissionState) {
        if (!cameraPermissionState.status.shouldShowRationale && !cameraPermissionState.status.isGranted) {
            cameraPermissionState.launchPermissionRequest()
        }
        onStopOrDispose { }
    }
```
