### ISSUE TITLE
[Flow layouts] Intrinsic measurements not calculated correctly

### ISSUE THREAD

**Issue by Tomasan7** [google/accompanist#1236]
**Description**

When using the `Modifier.height(IntrinsicSize.Min)` in a parent of the `FlowRow`, the parent straches in height significantly more than needed.

**Steps to reproduce**

Running this code snippet in Jetpack Compose:
```kotlin
Row(Modifier.height(IntrinsicSize.Min)
            .width(200.dp)
            .background(Color.White)) {
    FlowRow {
        repeat(50) {
            Text("Hello")
        }
    }
    Divider(Modifier.width(40.dp).fillMaxHeight(), color = Color.Red)
}
```
Result:
![actual](https://user-images.githubusercontent.com/47734291/178052246-d499ca4e-dbda-4354-959b-197f1094ad85.png)

**Expected behavior** 

The whole `Row` should be as high as the `FlowRow`'s minimal high is.
Expected:
![expected](https://user-images.githubusercontent.com/47734291/178052240-92c182f3-2d16-458f-b043-1297b0753ed4.png)

**Additional context**

I am using `com.google.accompanist:accompanist-flowlayout:0.24.13-rc` dependency for the `FlowRow`.

**Comment by Martinwagner-novasa** [comment]
I've run into the same issue as you. 
After some searching I found this workaround that should solve your problem too. Your code would then look something like this:
```
var height by remember { mutableStateOf(0) }
    Row(Modifier.onSizeChanged { height = it.height }
        .width(200.dp)
        .background(Color.White)) {
        FlowRow {
            repeat(50) {
                Text("Hello")
            }
        }
        Divider(Modifier.width(40.dp).height(with(LocalDensity.current) { height.toDp() }), color = Color.Red)
    }
```

Found it in this Medium article: [https://medium.com/@lepicekmichal/compose-intrinsic-redraw-bug-2cdecef0f96c](https://medium.com/@lepicekmichal/compose-intrinsic-redraw-bug-2cdecef0f96c)

I hope this immediate fix helps you, and that we wont have to make workarounds like these in the future :)

**Comment by distinctdan** [comment]
So I did some more digging on this, and I now see what's going on here. As it turns out, FlowRow is actually working correctly, the problem is that Compose's intrinsics don't use real measurements. Here's a walkthrough of what's going on under the hood:

Let's say we have 3 pieces of text that are in a FlowRow:
```
[Text1] [Text2] [Text3]
```

First, Compose is going to calculate its intrinsic measurements because we're using an intrinsics modifier. It calls FlowRow, and when FlowRow tries to measure each item, Compose expands each item's size to fill its constraints. This is because intrinsics use approximations instead of actually measuring. This causes each Text to fill the entire row:
```
[Text1                                           ]
[Text2                                           ]
[Text3                                           ]
```

Compose takes the height of this result and uses it to set a fixed height on the element that specified `Modifier.height(IntrinsicSize.Min)`. The rest of the output is thrown away. Finally, after potentially several passes, Compose will do a pass with real measurements. However, the height from the intrinsics pass is still used for the parent element. So we end up with the items in a row, but the parent has too much height:
```
[Text1] [Text2] [Text3]


```

Unfortunately intrinsics just aren't compatible with custom layouts or things that potentially may wrap to multiple lines, because the only way to get the correct size is to do real measurements. Personally, I think it would be more useful for intrinsics to use real measurements, but that's the way it currently is. Alternatives include using Layout or ConstraintLayout instead of intrinsics.
