### ISSUE TITLE
[Pager] Scroll gets stuck when pager indicators are present on Android 13

### ISSUE THREAD

**Issue by mariusmorabosch** [google/accompanist#1357]
**Description**
When scrolling back and forth on a horizontal pager with indicators, sometimes the fling doesn't work properly (similar to the effect of you not scrolling enough to make it switch page) when swiping from first to second or fifth to fourth (you need to scroll back and forth a couple of times, repro is not 100%). This seems to happen only on Android 13.

**Steps to reproduce**
Create a pager with 5 pages (just put some text on it) and page indicators, then scroll back and forth on the first and second pages. See attached video for details. You also can use the following sample demo project to reproduce: 

https://github.com/mariusmorabosch/horizontal_pager_bug_repro

https://user-images.githubusercontent.com/26637326/192823506-a2a09a1f-acc0-4b40-92b7-6dcdef909b9c.mp4

**Expected behavior** 
The scroll works properly and always changes page correctly. If you remove the pager indicators it seems to work properly

**Additional context**

**Comment by amaslanka** [comment]
Hi! I can confirm that I have a similar issue, it happens when you scroll rapidly between the first and second page. Are there any plans to fix it?

**Comment by amaslanka** [comment]
Bumping up my question.

**Comment by Levi-Moreira** [comment]
Hi, thanks for reporting this! I had a look at the issue and I was able to reproduce it a couple of times. Since this seem to be an issue in the fling behavior I'd point to snapper for help, but the lib has been deprecated in favor of the foundation fling version which we won't adopt in Accompanist because the foundation Pager version has been released and it wraps up the fling behavior and the pager. 

I gave your issue a try in the foundation implementation and it seems it doesn't exist there so I'd suggest you to have a look and report anything you find (in the issue tracker). Thanks!
