### ISSUE TITLE
[Permissions] Alternative for launchPermissionRequest with result

### ISSUE THREAD

**Issue by MaximPestryakov** [google/accompanist#1367]
**Description**
After launching permission request I need to performa some action depending on result but with current API it's impossible to do. It would be convenient to have method similar to `launchPermissionRequest` but `suspend` and with return value:

```kotlin
fun launchPermissionRequest(): Unit

suspend fun launchPermissionRequestSuspend(): PermissionStatus
```

Like it's done in KPermissions: https://github.com/fondesa/kpermissions/blob/d1be1e5c60d94fa472cba8ba25cacde59db67c9f/kpermissions-coroutines/src/main/kotlin/com/fondesa/kpermissions/coroutines/SuspendExtensions.kt#L32

**Comment by MaximPestryakov** [comment]
> There is the `onPermissionResult: (Boolean) -> Unit = {}` lambda passed to `rememberMutablePermissionState`, which is called upon getting a result from the permission request. Does that solve your issue here?

It's old-style approach with callbacks. It's much more convenient to have `suspend` method instead of callbacks. I think Kotlin (and especially Compose) promote less use of callbacks in favor of `suspend` functions. For example, [Compose Gestures API](https://developer.android.com/reference/kotlin/androidx/compose/foundation/gestures/package-summary)

**Comment by ianhanniballake** [comment]
Any permission based API that is `suspend` or callback based is **never** going to consistently work - that library included.

This is because there is no guarantee that the composable/activity that starts the request is actually still there when the request is returned as explained on the [Getting a result documentation](https://developer.android.com/training/basics/intents/result#register):

> When starting an activity for a result, it is possible (and, in cases of memory-intensive operations such as camera usage, almost certain) that your process and your activity will be destroyed due to low memory.
>
> For this reason, the Activity Result APIs decouple the result callback from the place in your code where you launch the other activity.

You can verify this by:
- Rotating your device while a permission prompt is visible (this causes a configuration change)
- Turning on 'Do not keep activities' in Developer Options to simulate low memory conditions (this causes your entire activity instance to be unconditionally destroyed)

The callback will always need to be separate from the launch.

**Comment by UKMIITB** [comment]
I am unable to access `rememberMutableMultiplePermissionState`
Only getting access to `rememberMultiplePermissionsState` which doesn't accept any lambda parameter

**Comment by alexvanyo** [comment]
`rememberMultiplePermissionsState` accepts a lambda that will be called with a `Map` of the permissions:
https://google.github.io/accompanist/api/permissions/com.google.accompanist.permissions/remember-multiple-permissions-state.html
