### ISSUE TITLE
[WebView] use WebViewCompat

### ISSUE THREAD

**Issue by ber4444** [google/accompanist#1390]
**Description**
You are using classes like `android.webkit.WebView` instead of using `androidx.webkit:webkit`.

**Comment by bentrengrove** [comment]
I don't think there is an androidx version of `android.webkit.WebView` specifically. Can you be more specific about which classes or methods are causing you an issue?

**Comment by bentrengrove** [comment]
You don't actually instantiate WebViewCompat though, it's a set of static functions you can call with a android.webkit.WebView. Compose has a minimum API of 21, so I am not sure what adding these compat libraries would do as it seems to be for supporting older API versions. 

If there is a specific issue you are running into please add that, otherwise I don't see the need currently as it would just pull in an additional dependency by default for no gain and if users need it, they could pull that dependency in themselves.
