### ISSUE TITLE
[Insets] Adding statusBarPadding with imePadding produces a jerk effect on hiding keyboard

### ISSUE THREAD

**Issue by HumairaPasha** [google/accompanist#1402]
**Description**
I'm adding Modifier.statusBarPadding().imePadding() to my sheet composable. The keyboard shows up fine but when the keyboard is dismissed the sheet moves down by status bar padding amount and then resumes its correct position producing a bounce effect. 

**Steps to reproduce**
This issue can be reproduced by using the statusBarPadding() followed by imePadding() on ModalBottomSheetLayout.

```
ModalBottomSheetLayout(modifier = Modifier
      .statusBarsPadding()
      .imePadding(), sheetState = state, sheetContent = { //.. }
    ) {
//....
}
```

**Expected behavior** 
Status bar padding should not be applied again on hiding keyboard. Transition should be smooth.

**Additional context**
The bounce effect can be seen in the attached video. (Playback speed 0.5 should help notice the bounce)
https://user-images.githubusercontent.com/35308325/202472216-721855e1-75f2-4906-a805-33e2de888670.mp4

**Comment by alexvanyo** [comment]
Is this using the accompanist/insets library, or the androidx.compose.foundation insets?

If you're using accompanist/insets, I'd recommend migrating to the androidx version since the accompanist version is deprecated and we don't intend to make further changes there.

If this is the androidx version, I'd report a bug on the main Compose [issue tracker](https://issuetracker.google.com/issues?q=componentid:612128)

cc @jossiwolf since this is modal bottom sheet related, who might know if this is already tracked somewhere.

**Comment by jossiwolf** [comment]
Thanks! We're looking at similar issues currently. Please file an issue on the Compose issue tracker and link it here :)

**Comment by HumairaPasha** [comment]
Thanks for the response guys! 
I have created the issue [here](https://issuetracker.google.com/issues/261744064).
