### ISSUE TITLE
[System UI Controller] Cannot hide the system navigation when Dialog appears

### ISSUE THREAD

**Issue by hamidreza-sani** [google/accompanist#1415]
## Describe the bug
I have a full screen application for a kiosk and when the dialogs show up the system navigation appears as well.

## To Reproduce
Open a dialog and the system navigations pop up. 
In my navigator I have this code:
```
val systemUiController: SystemUiController = rememberSystemUiController()
systemUiController.isStatusBarVisible = false // Status bar
systemUiController.isNavigationBarVisible = false // Navigation bar
systemUiController.isSystemBarsVisible = false // Status & Navigation bars
systemUiController.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
```

And I have also included it in the Dialog Composable as well:
```
@Composable
fun AboutDialog(
    clientId: String = "123",
    hardwareId: String = "5530353038340c1e0a",
    softwareVersion: String = "0.19.0",
    firmwareVersion: String = "0.0.8",
    usbConnected: Boolean = true,
    confirmText: String = "OK",
    onDismiss: () -> Unit = {},
) {
    val systemUiController = rememberSystemUiController()
        systemUiController.isStatusBarVisible = false // Status bar
        systemUiController.isNavigationBarVisible = false // Navigation bar
        systemUiController.isSystemBarsVisible = false // Status & Navigation bars
        systemUiController.systemBarsBehavior =
            WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE

    AlertDialog(
        onDismissRequest = { onDismiss() },
        confirmButton = {
            TextButton(onClick = onDismiss)
            { Text(text = confirmText) }
        },
        title = {
            Text(
                text = stringResource(id = R.string.about_header),
                fontWeight = FontWeight.Bold,
                style = MaterialTheme.typography.h5
            )
        },
        text = {
            Column() {
                Text(
                    text = stringResource(id = R.string.about_description),
                    color = TextPrimary,
                    style = MaterialTheme.typography.h6
                )
            }
        },
        modifier = Modifier
            .width(600.dp)
            .clip(RoundedCornerShape(12.dp)),
    )
}
```

## Expected behavior
For the system navigations to stay hidden

## Screenshots?
[Here](https://i.stack.imgur.com/Xcj0i.gif) is a gif that shows the issue

## Environment:
 - Android OS version: 12
 - Device: Samsung A7 Lite
 - Accompanist version: 0.27.0

**Comment by alexvanyo** [comment]
The implementation for showing a `Dialog` results in a distinct underlying `Window` being used. Since `SystemUiController` is modifying the `Window` properties, you'd need two distinct `SystemUiController`s created for each of the `Window`s to affect both.

Right now, the `rememberSystemUiController()` call in `AboutDialog` isn't occurring inside the `AlertDialog` call, so it is likely modifying the same outer window as the other calls.

I'd try moving the `rememberSystemUiController()` "inside" the `AlertDialog` call, and seeing if that allows for the effect you're going for. There isn't a super nice place to put it, but I'd try inside your `confirmButton` UI since that should always be called:

```kotlin
        confirmButton = {
            val dialogSystemUiController = rememberSystemUiController()
            TextButton(onClick = onDismiss) { Text(text = confirmText) }
        },
```

**Comment by hamidreza-sani** [comment]
Awesome. That did the trick @alexvanyo
I do have a similar issue with `DropDownMenu` as well and following your advice I added systemUiController inside it's context but the navigation system still appears when I click on the 

```
DropdownMenu(
                expanded = expanded,
                onDismissRequest = { expanded = false }
            ) {
                val menuDropDownSystemUiController = rememberSystemUiController()
                menuDropDownSystemUiController.isStatusBarVisible = false // Status bar
                menuDropDownSystemUiController.isNavigationBarVisible = false // Navigation bar
                menuDropDownSystemUiController.isSystemBarsVisible =
                    false // Status & Navigation bars
                menuDropDownSystemUiController.systemBarsBehavior =
                    WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE

                DropdownMenuItem(onClick = { onClickStoreName() }) {
                    Text(
                        text = storeName,
                        fontWeight = FontWeight.Bold
                    )
                }
      }
}
  ```

Any recommendations on how to handle this case?

**Comment by YugeCse** [comment]
It's true, I had received the problem,too.

**Comment by alexvanyo** [comment]
That sounds like a similar issue at play, it looks like `Popup` (which `DropdownMenu` uses under the hood) doesn't have a `Window`, but adds a `View` directly to the `WindowManager`.

A couple things to try together:
- Based on https://stackoverflow.com/a/73375717 you could try making `DropdownMenu` non-focusable using `properties = PopupProperties(focusable = false)`
- You could try using the deprecated `ViewCompat.getWindowInsetsController(LocalView.current)` from inside the `DropdownMenu`. That method is deprecated because the `Window` is necessary to adjust some flags, but it might be enough for the case of hiding and showing the system bars.

**Comment by hamidreza-sani** [comment]
Awesome! That totally did the trick!
Thanks. All problems resolved and now I have a fully immersed application :)

**Comment by alexvanyo** [comment]
Good to hear! Did you have success on API 29 and below as well?

**Comment by hamidreza-sani** [comment]
@alexvanyo seeing this issue on ExposedDropdownMenu as well but there's no `PopupProperties` available there

**Comment by roberto-m** [comment]
Is there any similar solution for NavGraphBuilder.dialog ? I tried all the suggested solutions above, but none worked
