### ISSUE TITLE
[WebView] Other Compose content not rendered while WebView is loading

### ISSUE THREAD

**Issue by dkarv** [google/accompanist#1442]
**Description**
While the Accompanist WebView is loading a url (we show a CircularProgressIndicator) it stops other Composable content from showing up. The other content is just white/blank.
Please checkout this screencast of the issue: 
![webview](https://user-images.githubusercontent.com/3708591/206706418-348b59c7-bd73-4c4e-b097-ebc009006435.gif)

**Steps to reproduce**
1. Initialize webview, starts loading
2. content above is not shown before the url is loaded

**Expected behavior** 
1. Initialize webview, start loading
2. content above is shown all the time 

**Additional context**
The content above is not hidden or covered. It shows up as supposed in the Layout Inspector, it is just not shown on the real screen:
![Layout inspector](https://user-images.githubusercontent.com/3708591/206706765-b88e54cf-10c5-4809-aa90-66806e987807.png)

It seems like the WebView is internally blocking the other Compose rendering.

Compose Version: 1.3.1
Accompanist Version: 0.27.1

The WebView creation:
```
Box(modifier = modifier) {
        WebView(
            state = webviewState,
            client = webviewClient,
            chromeClient = webviewChromeClient,
            onCreated = {
                onCreated(it)
            }
        )
        val loadingState = webviewState.loadingState
        if (loadingState is LoadingState.Loading) {
            Box(
                modifier = Modifier
                    .padding(24.dp)
                    .fillMaxWidth(),
                contentAlignment = Alignment.Center
            ) {
                TestbirdsIndeterminateCircularProgressIndicator()
            }
        }
    }
```
The other content is in a Column, together with the WebView.
I'm happy about any help or workarounds for this issue. I can provide more information if needed.

**Comment by bentrengrove** [comment]
This happens because on the first load of a webview it loads the whole chromium engine and that blocks Compose's applyChanges from happening. It is something I want to fix but haven't found a workaround for yet. Out of interest, does setting a `Modifier.alpha(0.99f)` fix the problem for you?

**Comment by dkarv** [comment]
Setting the alpha on the WebView fixed it on 3 out of 6 devices we tried.
It works:

- Samsung (Android 9)
- OnePlus 8T (Android 13)
- Emulator Android 13

Does not work:

- Huawei (Android 10)
- Pixel 2 (Android 11)
- Emulator Android 11

Based on the data it seems the fix does not work on Android 10 and 11 (we did not test Android 12).

**Comment by nicolashaan** [comment]
I have similar issues with the following snippet:
```
    val state = rememberWebViewState("https://www.notion.so")
    val navigator = rememberWebViewNavigator()
    Column(Modifier.background(Color.Red)) {
        Row(
            modifier = Modifier
                .height(56.dp)
                .fillMaxWidth(),
            horizontalArrangement = Arrangement.Start,
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(onClick = {}) {
                Icon(
                    Icons.Default.ArrowBack,
                    contentDescription = "go back"
                )
            }
        }
        WebView(
            state = state,
            navigator = navigator,
            onCreated = {
                it.settings.javaScriptEnabled = true
            }
        )
    }
```
### Expected result:
<img width="400" alt="Screenshot 2023-01-11 at 12 27 31" src="https://user-images.githubusercontent.com/24221189/211795601-076e0206-747e-48ff-86d1-b559c4dadef2.png">

### Actual result (Xiami Mi8, Android 10):
<img width="400" alt="Screenshot 2023-01-11 at 12 37 23" src="https://user-images.githubusercontent.com/24221189/211796963-6c7984f1-c8af-4b55-939f-2f19d895811e.png">

@bentrengrove Could you confirm that it's the same root cause?

Here is a project reproducing the issue: https://github.com/nicolashaan/accompanist-webview-issue-repro

**Comment by smithaaron** [comment]
I have just encountered a similar issue. I notice that setting a height on the WebView fixes the problem, e.g. 
`WebView(
                            modifier = Modifier.height(300.dp),`
                            
I'm not a Compose expert, but this behaviour makes me assume that Column doesn't render its content until all Composables are finished measuring. Since the WebView is still loading it doesn't yet know its height, so this blocks the parent Column from rendering.

**Comment by lyubomir-ganev-iu** [comment]
I found by chance similar issue described on StackOverflow. One answer suggested to explicitly set the WebView's layer type to SOFTWARE like this:

`webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null)`

This solved all visible issue for us.

Here is the original answer:
https://stackoverflow.com/a/75247593

**Comment by benlu1117** [comment]
With `webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null)`, the content of webView doesn't show after load for me. Still looking for other solution

**Comment by waheed006** [comment]
This solves the issue:
`AndroidView(
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f),
            factory = {
                WebView(context).apply {
                    setLayerType(View.LAYER_TYPE_SOFTWARE, null)
                    webViewClient = WebViewClient()
                    loadUrl(item.link)
                }
            })`

**Comment by dip-yonghun-choi** [comment]
I share the webview with people who put the webview in the androidview. In my case, I struggled with the phenomenon that the header was not visible until the webview was loaded.

In my case, I processed headers and content using Columns, but using "Scaffold" solved this problem. 

I hope it helps people watching this. That's it.

**Comment by alvindizon** [comment]
`setLayerType(View.LAYER_TYPE_SOFTWARE, null)`  does not work if the content has GIFs

**Comment by ln-12** [comment]
I know this issue is closed by my search lead me here first, so I want to make it easier for others to find this.

It seems like to correct solution is to set `clipToOutline = true` on the webview instance. See the (issue tracker for reference)[https://issuetracker.google.com/issues/174233728#comment5] and  the (source code for the current recommendation)[https://github.com/androidx/androidx/blob/42d844f7f349384761bca5dad6adaed43a8ae677/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/viewinterop/AndroidView.android.kt#L175].

@bentrengrove would you agree with that?

**Comment by bentrengrove** [comment]
Yes, I believe that is correct

**Comment by Rissmon** [comment]
Below code worked for me:

```

AndroidView(modifier = modifier, factory = {
        WebView(it).apply {
            //setBackgroundColor(Color.Blue.toArgb())
            clipToOutline = true
        }
    }, update = {
        it.loadDataWithBaseURL(null, html, "text/html", "UTF-8", "")
    })
```

**Comment by HeGuoPing917** [comment]
Integrating WebView in Compose also causes native crash on some devices. Wrapping it in FrameLayout seems like a better solution.

https://wbrawner.com/2024/08/28/android-webview-crash-in-jetpack-compose/
https://github.com/react-native-webview/react-native-webview/pull/2874
