### ISSUE TITLE
[Navigation Material] Standard (persistent) bottom sheet layout support

### ISSUE THREAD

**Issue by GoldenSoju** [google/accompanist#1461]
**Description**

At the moment I can only see support for ModalBottomSheetLayout, but I am wondering if the [material 3 standard bottom sheet](https://m3.material.io/components/bottom-sheets/overview) will also be supported in the future?

With the modal bottom sheet open, the user cannot interact with the active screen.

**Comment by jossiwolf** [comment]
Hi, we only offer support for modal bottom sheets.

> Like dialogs, modal bottom sheets appear in front of app content, disabling all other app functionality when they appear, and remaining on screen until confirmed, dismissed, or a required action has been taken.

Modals make sense as global navigation routes because they are independent and not tied to local content.

> Standard bottom sheets co-exist with the screen’s main UI region and allow for simultaneously viewing and interacting with both regions

Standard bottom sheets are tied to a specific screen, thus a navigation destination for them does not provide any benefit.

We currently don't see any use case for standard bottom sheet destinations.
