### ISSUE TITLE
[Navigation Material] Migrate or provide an M3 alternative

### ISSUE THREAD

**Issue by bentrengrove** [google/accompanist#1480]
NavigationMaterial is using Material 2, we either need to migrate it or provide an alternative version that references m3

**Comment by amarnehSoft** [comment]
is there any updates on this?

**Comment by Nek-12** [comment]
What dependency are you waiting for?

**Comment by Bradleycorn** [comment]
Any updates on this?

**Comment by newmanw** [comment]
Curious on the state of this, is there a roadmap anywhere?  Linter is now complaining, only a warning, but would be nice to no longer depend on material2 for just this component.

> Using a material import while also using the material3 library

**Comment by ianhanniballake** [comment]
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

This issue was not fixed as part of the migration, so if you're still interested in this, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) and the Material team will take a look.

Include the link here so that others can star it!

**Comment by hrach** [comment]
We had a solution (integration of M3's Bottomsheet to Navigation Compose) for some time and I finally open-sourced it. Who knows for how long :) 

https://github.com/hrach/navigation-compose/
