### ISSUE TITLE
[Navigation Material] ModalBottomSheet won't open when windowSoftInputMode is set to adjustResize

### ISSUE THREAD

**Issue by jibe-n** [google/accompanist#1499]
**Description**
I noticed a bug after upgrading my project to Navigation Material `0.29.0-alpha`.

When `windowSoftInputMode` is set to `adjustResize` in the manifest and you navigate from a bottom sheet to a destination that uses the keyboard, you won't be able to open any bottom sheet after you navigate back.

I made a sample to reproduce this bug, available [here](https://github.com/jibe-n/ModalBottomSheetBug).

**Steps to reproduce**
Using the sample above, follow this steps to reproduce the behavior:
1. Click on the `Open Sheet` button
2. From the bottom sheet, click on the `Navigate to Screen B` button
3. Navigate back
4. Click on the `Open Sheet` button again, the bottom sheet cannot be opened anymore

**Expected behavior** 
The bottom sheet should be able to be opened again.

**Environment**
 - Accompanist version: 0.29.0-alpha
 - Compose version: 1.4.0-alpha05

**Additional context**
Removing `android:windowSoftInputMode="adjustResize"` in the manifest solves the issue.

**Comment by leinardi** [comment]
This issue is pretty annoying! I know that this is an alpha version of the library, but can we get at least an acknowledged that the bug is confirmed and a fix will be available for the next release?

**Comment by jossiwolf** [comment]
Thanks for the report, @jibe-n! The repro project is very helpful. We can repro the issue and are looking at the cause and possible fixes.

@leinardi I understand that this issue is annoying. While we are doing our best to reply to issues straight away, this is not always possible due to the high volume of traffic we see on both IssueTracker and here. We typically don't provide ETAs as the release timing depends on a multitude of factors. This also means we don't talk about the scope of the next release until we have at least merged the bugfix.

**Comment by vinipazzini** [comment]
Can we have a new version with this fix?

**Comment by jibe-n** [comment]
Fixed in v0.29.2-rc, thank you so much!
