### ISSUE TITLE
[Image Loading] Display something better when in Preview

### ISSUE THREAD

**Issue by chrisbanes** [google/accompanist#150]
Currently `CoilImage`, `PicassoImage`, and `GlideImage` all have different issues when used in `@Preview`. We should do something better.

- [ ] Make sure that using each of these functions does not crash the preview
- [ ] Think about adding a `placeholder` parameter to be displayed when in preview.

**Comment by Bradleycorn** [comment]
This may be a terrible/impossible idea (I'm still very new to Compose and in way over my head here), but ... 

Is there some way that you can "detect" that the composable is being rendered as a preview? 

If so, maybe when the `*Image()` composable detects that it's in preview mode, it attempts to use a (developer defined) `PreviewImageLoader` if it exists instead of its normal `ImageLoader`.  Defining a `PreviewImageLoader` could be as simple as defining a map of the url's that are used in previews to local resources to load when one of the url's is found? 

Or maybe you don't need the detection and `PreviewImageLoader` at all ... Maybe the developer could supply the standard `ImageLoader` with a map of url->drawable, and anytime the loader is asked to load one of those urls, it will use the drawable instead of trying to fetch the url. 


Another (probably really bad) idea ... when the `data` parameter is parsed and is a string, check to see if it's a URL or if its specifies drawable (like "R.drawable.my_preview_image"). If it's determined to be a drawable, the actual resource could be parsed out, and the drawable loaded and returned. Something like this extension method on R.drawable could be used to parse the drawable string into an actual drawable int:
```
fun R.drawable.fromString(drawable: String): Int {
    try {
        val field = javaClass.getField(drawable.replace("R.drawable.", ""))
        return field.getInt(field)
    } catch (ex: Exception) {
        TODO("Uh oh!")
    }
}
```

**Comment by chrisbanes** [comment]
I like the idea of a `PreviewImageLoader` _but_ `ImageLoader` isn't a class we own. Same for the equivalent classes for `GlideImage` and `PicassoImage`.

We could abstract these away behind a `ImageLoadEngine` class and do something similar though.

**Comment by chrisbanes** [comment]
Closing this, as `previewPlaceholder` was added a few releases ago.
