### ISSUE TITLE
[Placeholder] `this then composed` looks unintentional

### ISSUE THREAD

**Issue by efemoney** [google/accompanist#1525]
https://github.com/google/accompanist/blob/4f29fdb3c3c8c603c31e0e913d8cea7cf67c5c87/placeholder/src/main/java/com/google/accompanist/placeholder/Placeholder.kt#L112

You end up with a case where:

```kt
A.placeholder = (A + (A + ComposedModifier))
```

**Comment by alexvanyo** [comment]
Related to https://github.com/google/accompanist/commit/ced01228f45e00dee00dbafdd90326b016666687 which added that check here and elsewhere.

**Comment by alexvanyo** [comment]
Good catch, this short repro shows how the receiver `Modifier` instance is being applied twice like:

```kotlin
@Preview
@Composable
fun Repro() {
    Box(Modifier.padding(16.dp).yellowBackground().size(16.dp))
}

fun Modifier.yellowBackground(): Modifier = this then composed { background(Color.Yellow) }
```

<img width="238" alt="Screen Shot 2023-02-24 at 12 21 16 PM" src="https://user-images.githubusercontent.com/4217560/221283659-094411cf-9a3b-4aef-a7d9-5cca3fc26309.png">

This seems like a good candidate for a potential lint check, since it's not immediately obvious that this can lead to incorrect behavior.

**Comment by alexvanyo** [comment]
Reported https://issuetracker.google.com/issues/270963071 to potentially add that as a lint check.
