### ISSUE TITLE
[Pager] ExperimentalPagerApi deprecated but used in Indicators

### ISSUE THREAD

**Issue by barry-irvine** [google/accompanist#1551]
**Description**

In the v0.30.0 release the Pager classes were deprecated but it is still permitted to use the PagerIndicators and the `pagerTabIndicatorOffset` if using the Foundation `PagerState`. This now means that we have to opt-in to an experimental annotation which is now deprecated—this doesn't seem right.

**Steps to reproduce**

Create a pager using the foundation classes but still use the accompanist pager indicators.

**Expected behavior** 

Either the above classes should no longer require the deprecated `ExperimentalPagerApi`, the annotation should not be deprecated or we should have a new annotation like `ExperimentalPagerIndicatorApi`. (Of course, perhaps indicators are also included in Compose 1.5 and this is all moot).

**Additional context**

**Comment by PaulWoitaschek** [comment]
This is explicitly a problem with allWarningsAsErrors

**Comment by ZacSweers** [comment]
Another issue related to this - `HorizontalPagerIndicator` is also annotated with this

**Comment by joshrvezy** [comment]
this is still an issue with 0.30.1 inside the PagerTab class:   

@OptIn(ExperimentalFoundationApi::class)
@ExperimentalPagerApi
fun Modifier.pagerTabIndicatorOffset

its saying it was fixed by : Fixed by https://github.com/google/accompanist/pull/1555, however that PR does not include the PagerTab class change above

**Comment by bofcarbon1** [comment]
I picked up a code example in Geeks for Geeks dated July 2025. Using @ExperimentalPAgerApi. It worked.  Then when I converted to suggested library 'type safe' it wiped out the packages for ExperimentalPagerApi. Pain in the neck because of pager state introduced. Impossible to track across 4 composables. It was overkill to begin with but it worked.  Trying to get it back but the gradle build changes are just too messed up now. I was going to demo something for a client but I am turning my back on this shit show.  100 lines of code to just swipe pages left to right. Get the hell out of here.
