### ISSUE TITLE
Unable to set the same height of all items in horizontal pager in compose

### ISSUE THREAD

**Issue by Aadi1510** [google/accompanist#1562]
I want to get the highest height of all the items of horizontal pager and provide that height to all items, so that every pager has same height. Any pointers or help would be highly appreciated.

**Comment by bentrengrove** [comment]
Because Pager is a lazy component, this is not possible. You would have to Compose all the items in advance to achieve this and this would not be lazy. Perhaps in this case, just a simple Row with a snapping behaviour might be best.

As this question is about a deprecated component, I will close this issue. I would recommend questions like this be asked on Stack Overflow.
