### ISSUE TITLE
Create a BOM for the accompanist libraries

### ISSUE THREAD

**Issue by OliverRhyme** [google/accompanist#1608]
## Describe the bug
Adding a BOM to accompanist can improve the maintainability of the versions. 

## Expected behavior (if applicable)
A BOM is available

## Additional context
This will ease the versioning of the accompanist libraries (dev side) and reduces the chances of importing a wrong version and possibly inflating the APK.

**Comment by bentrengrove** [comment]
Accompanist libraries are all versioned as one, I'm not sure what this would actually help with? Can you give a more specific example please?

**Comment by bentrengrove** [comment]
The Compose libraries are actually versioned separately now which was the inspiration for adding the BOM, for example Compose m3 is on 1.1.0 where as the rest are on 1.5.0. We also anticipate there will be more divergence as time goes on. We also couldn't keep a BOM version number in sync with the Compose libraries to make matching easier because we release on different schedules unfortunately.

I will close this for now but if other people feel strongly about this then please do comment.
