### ISSUE TITLE
[Navigation Material] 

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#1773]
**Description**
In readme, it states that there are migration instructions. But they don't exist

**Comment by alexvanyo** [comment]
There hasn't been a release since the deprecation, so I don't think the docs have been staged to https://google.github.io/accompanist/.

In the meantime, you can view the Markdown file directly here which has the migration guide: https://github.com/google/accompanist/blob/main/docs/navigation-material.md

**Comment by ColtonIdle** [comment]
AH thanks.

I guess it was just bad timing on my part to be adding it to my project. Lol. Thanks! Great talk at IO btw!

Sent from Proton Mail Android

-------- Original Message --------
