### ISSUE TITLE
SwipeRefresh placed over TopAppBar when used inside BottomSheetScaffold

### ISSUE THREAD

**Issue by maxtomczyk** [google/accompanist#377]
## Describe the bug
`SwipeRefresh` inidicator is displaying over `TopAppBar` when used inside `BottomSheetScaffold`. The problem is not appearing when using `SwipeRefresh` inside `Scaffold`

## To Reproduce
Use `SwipeRefresh` inside `BottomsheetScaffold` with `TopAppBar`

## Expected behavior
Place `SwipeRefresh` indicator under `TopAppBar` like it's done when wrapped `Scaffold`

### Wrapped in `Scaffold`:
![2](https://user-images.githubusercontent.com/20241462/116526630-18f55400-a8da-11eb-8b68-0600502ea29c.PNG)

### Wrapped in `BottomSheetScaffold`:
![1](https://user-images.githubusercontent.com/20241462/116526641-1d217180-a8da-11eb-88de-2c78d274b651.PNG)

## Environment:
 - Android OS version: 11
 - Device: Emulator of Pixel 3A, API 30 x86
 - Accompanist version: 0.8.1

### Minimal code to reproduce issue:
```kotlin
@Composable
private fun TopBar() {
  TopAppBar() {
    Text(text = "Reproduction")
  }
}

@Composable
private fun RefreshableContent() {
  LazyColumn(Modifier.fillMaxWidth()) {
    items(100) {
      Text("Content is here")
    }
  }
}

@ExperimentalMaterialApi
@Composable
private fun Broken() {
  BottomSheetScaffold(sheetContent = {  }, topBar = {TopBar()}) {
    SwipeRefresh(
      state = rememberSwipeRefreshState(isRefreshing = false),
      onRefresh = {}) {
      RefreshableContent()
    }
  }
}

@Composable
private fun Correct() {
  Scaffold(Modifier.fillMaxWidth(), topBar = { TopBar() }) {
    SwipeRefresh(
      state = rememberSwipeRefreshState(isRefreshing = false),
      onRefresh = {}) {
      RefreshableContent()
    }
  }
}

class MainFragment : Fragment() {
  companion object {
    fun newInstance() = MainFragment()
  }

  @ExperimentalMaterialApi
  override fun onCreateView(
    inflater: LayoutInflater, container: ViewGroup?,
    savedInstanceState: Bundle?
  ): View {
    return ComposeView(requireContext()).apply {
      setContent {
        // Replace with Correct() to use Scaffold instead of BottomSheetScaffold
        Broken()
      }
    }
  }
}
```

**Comment by maxtomczyk** [comment]
Really simple walkaround I found is to use zIndex modifier on `TopAppBar`.

**Comment by chrisbanes** [comment]
We do not clip the indicator currently, to support use cases where the app bar is translucent and you actually want to see the indicator behind (see the samples).

I think this is actually a bug in `BottomSheetScaffold`. It looks like it is drawing the `topBar` content _after_ the main content (see [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/BottomSheetScaffold.kt;l=320)), which is why the indicator is drawing on top. `Scaffold` is doing the correct thing of drawing the content first. This is worth raising on the Compose bug tracker: http://goo.gle/compose-feedback.

I might add a parameter to clip the indicator, but using a `zIndex` on the `TopAppBar` is a fine fix too.
