### ISSUE TITLE
[SwipeRefresh] Update indicator to fade-in during drag

### ISSUE THREAD

**Issue by chrisbanes** [google/accompanist#431]
See https://github.com/android/compose-samples/issues/541

**Comment by chrisbanes** [comment]
@ricknout fancy taking this? (No worries if you're busy/ooo)

**Comment by ricknout** [comment]
I actually copied the implementation of the View version which also uses a transition instead of being tied to drag. Do you think this would be better?

**Comment by chrisbanes** [comment]
I'll leave that decision to @c5inco. Probably best to go off the spec?

**Comment by ricknout** [comment]
The closest thing we have to a spec is:
https://material.io/design/platform-guidance/android-swipe-to-refresh.html#behavior-placement

>  As the refresh indicator scales into view, the circular spinner fades in while rotating.

A little vague and open to interpretation 😅

**Comment by chrisbanes** [comment]
Haha, let's see what Chris says then! From the other issue, it sounds like Chris thinks it should be tied to the scroll

**Comment by c5inco** [comment]
Ah interesting - I didn't realize the View implementation had the same transition. I think when Farheen first filed the bug internally on Jetnews, we:

A) Didn't have this component built in Compose
B) Didn't have Accompanist (and the component)
C) Were working off interpretation of the Material guideline as I believe we tried to track down the original design spec but couldn't find it

All that being said, I think changing the transition behavior for Compose may actually not be ideal since it will introduce inconsistencies in hybrid apps. Now if we could change the View implementation to match, that would be great, but the ROI is probably not high enough?

**Comment by chrisbanes** [comment]
Personally I think we should do the ‘right thing’ going forward (in Compose). The difference here would be pretty minimal vs views, and we could follow up later to update the view impl.

So, what’s the right thing? Fade in the indicator from 0-100% linearly over a drag which = height of the (indicator + padding)?

**Comment by c5inco** [comment]
Given the vagueness in the original "spec", my designer instinct is to go with fading in the indicator over a drag (as you suggested).

Ultimately the right thing to do though is circle back with the Android UX motion design team to see what changes they'd like to see (if any). I can follow-up with them and update this issue once I hear back?

**Comment by ricknout** [comment]
SGTM. I'm happy to have a go at this (and to my eyes the indicator arc grow drawing seems to have changed against spec at some point so I'll investigate fixing that too)

**Comment by chrisbanes** [comment]
Great, thanks both!
