### ISSUE TITLE
Change page on clicking the indicator circle?

### ISSUE THREAD

**Issue by Sparsh123** [google/accompanist#508]
I am using "com.google.accompanist:accompanist-pager:0.11.1" and "com.google.accompanist:accompanist-pager-indicators:0.11.1". How do we make the indicator circles clickable such that clicking on an indicator circle takes us to the relevant page?

**Comment by dyelfeedbak** [comment]
Me gustaría poder actualizar mi realmente 7

**Comment by fornewid** [comment]
Looking at the [`PagerIndicator`](https://github.com/google/accompanist/blob/main/pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt#L145) implementation, it doesn't support clicks.
But since the click area seems too narrow, so does it make sense to support clicks? 🤔 

PagerIndicator was implemented very simply.
So I think, you can make custom pager indicator easily.

If we want to add functionality to current implementation, we need to add `clickable`s to `indicatorModifier`.

**Comment by Sparsh123** [comment]
@fornewid , would be really kind of you if you provide the code for adding clickability to indicatorModifier.

**Comment by chrisbanes** [comment]
This isn't an issue. Moving to discussions.
