### ISSUE TITLE
[Idea] Migrate libraries over to KMP

### ISSUE THREAD

**Issue by chrisbanes** [google/accompanist#552]
TODO

Experiment in #393

**Comment by JavierSegoviaCordoba** [comment]
Multiple projects can be transformed into Multiplatform easily, do you accept pull requests for them?

Another question, similar to Jetsnack, I am implementing a custom theme that fallbacks to `MaterialTheme`. The implementation uses `rememberSystemUiController()`, which has sense in Android, but no sense in Desktop. Do you think this library should be transformed to KMP? The problem is if it is only Android, I have to do manually an `expect/actual` that does nothing in other platforms because the theme implementation is for all themes, so maybe instead of forcing to do manually this "void" `expect/actual`, it can be done by the library, so it can be implemented in `commonMain` directly.

**Comment by AshStefanOltmann** [comment]
@chrisbanes Can you reopen and remove the label?

**Comment by wakaztahir** [comment]
Please reopen this issue , These libraries should support KMP
