### ISSUE TITLE
[Pager] Offset screens are not recomposed when their state change

### ISSUE THREAD

**Issue by offvanHooijdonk** [google/accompanist#771]
See /issues/706
Still reproduces within v0.19.0 . As now initialOffscreenLimit is not set, the recomposition of page happens if you scroll 2 screens forward.

**Comment by andkulikov** [comment]
Hello! I will take a look on this issue if you can provide a code sample reproducing the issue. Thanks

**Comment by offvanHooijdonk** [comment]
@andkulikov Thank you so much! Was making a lib, but whole thing is pointless having this issue.
There you go: https://github.com/offvanHooijdonk/compose-datepicker/blob/4b66b324940eddf717edb89d5d7a6b9522bbb636/datepicker/src/main/java/by/offvanhooijdonk/compose/datepicker/dialog/DatePickerDialog.kt#L123

**Comment by andkulikov** [comment]
I took a look on your implementation and there is nothing wrong with Pager. What you are doing wrong is how you manage the state. You should always have only one source of truth, but in your case all of your composables have their inner state with the current item and also notify its parent about this change. With such implementation your internal and external states can easily be out of sync. 
It is ok that you have inner state inside DatePickerDialog as you want to only notify the parent when the button click happened. But all other layers shouldn't have their own state. So remove `val pickedDate = remember { mutableStateOf(initialPickedDate) }` from DatePickerPager and DatePickerLayout and just use the date you got from the function param as you do in DatePickerLayoutMonth.
Why it sometimes work for you because Pager usually destroys pages which are not visible with their inner state, but it is completely ok that nearest pages are not destroyed, so they are not destroyed and their inner state is now out of sync from the global state

**Comment by offvanHooijdonk** [comment]
@andkulikov  Thank you so much for your effort and you comments. 
This is my first try to make something not-that-little with Compose, and a luck for me someone took time for a feedback. I'm longing for using Compose in production, but out of luck so far.
I'll defenetly go for refactoring my code, hope doing my best would be enough to make this work  (God find me time).
And thanks for Accompanist, that is huge!
Полагаю, ты тоже русскоязычный, напишу нормально: огромное спасибо! Очень хочу в Compose, но Compose в продакшен пока редкость, и как есть время - пытаюсь; и качественный фидбек очень важен ) И большой респект всем за библиотеку, это очень классно! 🤝 🚀

**Comment by andkulikov** [comment]
Успехов в изучении Compose :)
