### ISSUE TITLE
rememberPagerState() update makes basing two Pagers off of one state impossible?

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#820]
## Describe the bug
I was using rememberPagerState() populated with an initial page count because I have two different pagers on the screen that are driven by a single state. Now that page count has to be passed as an arg into HorizontalPager, it seems like that ability is now lost.

## To Reproduce
This is what I was using before and I was driving two pagers off of this state.

val pagerState =
        rememberPagerState(
            pageCount = viewModel.state.items.size)

Am I doing something wrong? When I scroll through one pager, the other pager doesn't change.

Edit: Another example of things not working correct is that I have Text(pagerState.currentPage) and that doesn't update ever. It starts at 1, and even though I'm scrolling through my HP it just stays at 1. This was also working before but is now broken. I'm assuming this is because my pagerState doesn't know how many items and therefore doesn't know it's current page?

**Comment by andkulikov** [comment]
Hey! yes, one PagerState or LazyListState cannot really be used with multiple components. reason is your different components can be displaying different content - with different items count, or different items sizes, different content paddings. If we take Pager as an example, imagine they display items with different content padding, then in order to scroll from one item to the next one they need different amount of pixels to be scrolled. Even for PagerState it was mostly accidentally working for you previously.
It should be theoretically possible to just sync the scroll positions of two states, like when one changes do similar change for another one
