### ISSUE TITLE
[Undo system bar colors changes]

### ISSUE THREAD

**Issue by rustamsmax** [google/accompanist#877]
**When used with a navigation of a screen with default color and screens with different colors we must call setNavigationBarColor for every screen in order to work properly**

**We could call on enter a screen setNavigationBarColor and onDispose call undoNavigationBarColor**

![image](https://user-images.githubusercontent.com/36570577/141772819-7b141016-3d72-48ca-ac47-1dc1244872b5.png)

**Comment by ianhanniballake** [comment]
In general, you shouldn't be doing this kind of change as part of each individual screen. Like [other cases of changing your global UI](https://github.com/google/accompanist/issues/633#issuecomment-942988181), you'd instead want to use what destination you are on as the source of truth for what your navigation bar color should be, using APIs like the `visibleEntries` API on `NavController` to coordinate when you change the color with when that screen appears.

By having Navigation be your single source of truth, you automatically 'undo' navigation bar color changes when you return to the previous screen.

Note that you might consider [arguments as your source of truth](https://developer.android.com/guide/navigation/navigation-ui#argument): rather than hard coding a map of destination to color, you can encode that as an argument that **isn't** part of your route but gets its value solely from the `defaultValue`, essentially attaching static data to each destination as part of Navigation's APIs.
