### ISSUE TITLE
[Navigation] Blank screen when using BottomBar and navigating to a different screen

### ISSUE THREAD

**Issue by axelbau24** [google/accompanist#944]
**Description**
I'm tryng to use a bottom nav bar inside a Scaffold to have a separated navigation between "Main" screens and other screens (that don't include the nav bar)
But I encountered an issue when doing so, when i try navigate to a different screen (from the main navigation graph, the screen turns white while animating, the strange thing is that the navbar transitions correctly, but no the NavHost inside it.

Here's an example of whats happening:

![image](https://i.imgur.com/WfZ9yeq.gif)

You can see the full code in my example project that reproduces this issue.
https://github.com/axelbau24/AccompanistIssue/blob/master/app/src/main/java/com/app/accompanisnavissue/MainActivity.kt

**Additional context**
compose_version = '1.1.0-rc01'
accompanist_version = '0.22.0-rc'

I found this when updating versions, previously I was using the following versions and it worked fine:
compose_version = '1.0.5'
accompanist_version = '0.20.2'

**Comment by jbw0033** [comment]
This behavior is actually expected.

What is happening is that there is a child NavHost inside of the backStackEntry of its parent NavHost. When you try to navigate to a different screen in the parent, you are actually causing the backStackEntry that the child is in to immediately move its Lifecycle to CREATED, which forces the child's lifecycle to CREATED as well, and AnimatedNavHost can only show screens when the Lifecycle is at least STARTED.

When you nest graphs using the `navigation` composable, because the root graph is aware of all of its children, we can hold Lifecycle changes until transitions complete, but when you nest this in this way, the host, in this case the backStackEntry, is completely unaware of anything going on inside of it since the Lifecycle is a one way relationship.

So unfortunately, this is not a use case that is supported.
