### ISSUE TITLE
[Pager] Can't use HorizontalPagerIndicators without HorizontalPager

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#954]
**Description**
This is a bit of a weird one and I'm okay with you closing this as an unsupported use case... but it used to work in 0.17, but it doesn't when using 0.22

This code used to work 

```
val pagerState = rememberPagerState(...)

  LaunchedEffect(something) {
      pagerState.scrollToPage(lastPage)
  }

      HorizontalPagerIndicator(
          pagerState = pagerState
      )
```

but after updating from 17 to 22, I noticed that the indicator didn't move anymore.

I now have to add a dummy HP in order to get my old code to work:

```
val pagerState = rememberPagerState()

  LaunchedEffect(something) {
      pagerState.scrollToPage(lastPage)
  }

  HorizontalPager(
      count = mylist.size,
      state = pagerState,
      modifier = Modifier.fillMaxWidth().height(0.dp), <---- size(0.dp) didn't work. had to give it at least a width for pagerState to update
  ) { page -> }

      HorizontalPagerIndicator(
          pagerState = pagerState
      )
```

Again. I'm doing some weird stuff I guess because I only need the indicators and not the pager itself. Wanted to bring it up though as I guess it might have been an unintentional change. cheeerrs

**Comment by andkulikov** [comment]
Hey!
It is the intentional change. It is a state of the Pager component, it shouldn't be used without a Pager component. I can agree that it could be useful to have an overload of HorizontalPagerIndicator accepting raw values which you can manually animate so it is decoupled from the PagerState. However, given that this composable https://github.com/google/accompanist/blob/main/pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt is quite small why don't you just copy it and modify as you need for your custom use case?
