### ISSUE TITLE
[Insets] Scaffold bottomBar cutout is not working

### ISSUE THREAD

**Issue by Zeliret** [google/accompanist#958]
Hello!
I've noticed that if I replace basic Scaffold with a new one from Insets library my cutout shape disappears. 

**Steps to reproduce**
Just replace default Scaffold with a new one.

**Expected behavior** 
Cutout shape should be applied.

**Additional context**
![Screenshot_1642340140](https://user-images.githubusercontent.com/975526/149662450-b1d94e51-e1c5-4d9c-b775-d68378c0f1aa.png)
![Screenshot_1642340431](https://user-images.githubusercontent.com/975526/149662521-0101ad1d-f888-4636-a104-d59293742d69.png)

**Comment by alexvanyo** [comment]
Hi Zeliret! For the basic Scaffold that does work (the one that isn't provided by Accompanist), is that a `material` Scaffold or a `material3` scaffold?

**Comment by Zeliret** [comment]
Hi. It is material.

Best regards,
Artem

**Comment by Zeliret** [comment]
Still doesn't work. =(

**Comment by panzerfahrer** [comment]
Seeing this with `0.24.9-beta`

@alexvanyo could you check if this could be fixed, please?

When debugging, it seems that `LocalFabPlacement` yields `null` in the `BottomBar`, altough it gets correctly assigned.

**Comment by alexvanyo** [comment]
I was able to track down what's happening here:

There ends up being two `LocalFabPlacement` compositions locals.

One that is defined by `androidx.compose.material`, [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/Scaffold.kt;l=367;drc=5f442ff2a5ea30cc8d49888554a31d20c66c9dce).

And the other that is defined by `accompanist/insets-ui`.

Unfortunately, both of them are `internal`, which means that they can't be read by components outside of the respective libraries. In particular, the `androidx.compose.material.BottomAppBar` is reading its `androidx.compose.material.LocalFabPlacement`, but only the `com.google.accompanist.insets.ui.LocalFabPlacement` is being set by the accompanist `Scaffold`.

The fix for this on the accompanist side would look like duplicating all of `BottomBar` and its dependencies, so that the right `LocalFabPlacement` is used. That solution is also what the workaround would be right now for you: fork `Scaffold` and `BottomBar` yourself, and ensure your own `LocalFabPlacement` is being used.

Alternatively the only reason why `Scaffold` needed to be used was for passing the height of the top app bar to the content padding. If you aren't making use of that, or you can switch to `material3`, then you won't need to use the accompanist version of `Scaffold`.

**Comment by Zeliret** [comment]
I saw that compose supports insets and migrated to it. And now I can use the original scaffold without any problem.

**Comment by panzerfahrer** [comment]
As @Zeliret pointed out, compose foundation supports insets since 1.2.0-alpha03.

This yields visually the same result as with accompanist Scaffold:
```kotlin
import androidx.compose.material.Scaffold
import androidx.compose.foundation.layout.statusBarsPadding

Scaffold(
  modifier = Modifier.statusBarsPadding()
 ) { scaffoldContentPadding ->
  // ...
}
```

**Comment by alexvanyo** [comment]
A change was just made to `material3` that will include inset support for `Scaffold`, the `BottomNavBar` and `Fab`, so I'm going to close this issue as not planned.

A version of `acccompanist/insets-ui` for `material3` should be unnecessary, as the relevant changes needed have been upstreamed.
