### ISSUE TITLE
[Navigation] [ModalBottomSheet] ON_DESTROY NavBackStackEntry never triggered

### ISSUE THREAD

**Issue by Fgabz** [google/accompanist#978]
Hello ! 👋

**Description**
I'm listening to the lifecycle of the NavBackStackEntry in my application. When the Lifecycle enters in the `ON_DESTROY`, I'm doing some clean up. 

If I click outside the ModalBottomSheet or if I swipe down the `ON_DESTROY` event is reached. However when I press the back button the last lifecycle event reached is `ON_STOP`

**Steps to reproduce**

```
fun NavBackStackEntry.listenLifecycle() {

    // This avoid to be called multiple times because of recomposition
    DisposableEffect(Unit) {
        val observer = LifecycleEventObserver { _, event ->
            println("[Test] $event")
            if (event == Lifecycle.Event.ON_CREATE)
                //Do some stuff
            
            if (event == Lifecycle.Event.ON_DESTROY)
                //Do some stuff
        }

        lifecycle.addObserver(observer)

        onDispose {
            lifecycle.removeObserver(observer)
        }
    }

}
```

**Expected behavior** 

Whatever the usecase used to dismiss the modal bottom sheet, the `ON_DESTROY` should be triggered

**Additional context**

**Comment by FunkyMuse** [comment]
Found the same bug, `ON_DESTROY` is only called when you swipe down the bottom sheet by hand and not if you tap outside the sheet layout (basically if you tap on the scrim it's not called).

**Comment by jossiwolf** [comment]
Thank you for confirming! I'm still investigating, but it does look like we should be moving to the destroyed state.

**Comment by FunkyMuse** [comment]
Can we reopen this? @jossiwolf

**Comment by FunkyMuse** [comment]
@jossiwolf

**Comment by micHar** [comment]
@jossiwolf any updates here?

**Comment by FunkyMuse** [comment]
@jossiwolf same issue is also for `dialog()` composable, it never reaches onDestory

**Comment by FunkyMuse** [comment]
Now there's an [issue tracker](https://issuetracker.google.com/issues/232420198) too

**Comment by FunkyMuse** [comment]
@jossiwolf I don't wanna seem pushy towards an answer but if i were to use a dialog and set a result to the previous backstack entry i wouldn't get it because the state never reaches onDestroy, is there some workaround temporarily? I tried finding something similar like for the bottom sheet but i wasn't unable to.

Also this is more serious issue since onDestroy is never called and resources are there for the dialogs called...

I think this issue should be high priority but there hasn't been a response on this for a very long time and it seems pretty damaging to have an issue on something so important for everyone who uses the nav component with Compose

**Comment by micHar** [comment]
Not stale

**Comment by agent10** [comment]
The same issue happens for me.
