### ISSUE TITLE
[Insets] Chromebook ime insets wrong on maximize window

### ISSUE THREAD

**Issue by jannisveerkamp** [google/accompanist#985]
**Description**
```
LocalWindowInsets.current.ime.isVisible
```
returns true on my Chromebook when I maximize the window size. It works when I resize the windows manually to a full size or entering Fullscreen Mode (F4).

**Steps to reproduce**
Maximize the windows size of the app (on the top right of the window next to the close button).

**Expected behavior** 
`LocalWindowInsets.current.ime.isVisible` still returning false

**Additional context**
I think the Chromebook doesn't even have an IME 😬 

My Setup:
- Chrome OS Version: 97.0.4692.102 (64 Bit)
- Android Version: 9

**Comment by alexvanyo** [comment]
Hello! Could you provide a bit more information about your setup?
- Is your activity using `android:windowSoftInputMode="adjustResize"`
- What is your Chrome OS version, and the Android version on Chrome OS?

**Comment by jannisveerkamp** [comment]
I've added my setup

**Comment by alexvanyo** [comment]
Just to confirm, are you using `android:windowSoftInputMode="adjustResize"` in your Activity?

**Comment by jannisveerkamp** [comment]
I'm using this: `android:windowSoftInputMode="stateHidden|adjustResize"`

Sorry 😬

**Comment by 52541** [comment]
but idont know.

**Comment by jannisveerkamp** [comment]
still relevant

**Comment by alexvanyo** [comment]
Since accompanist/insets is being deprecated in favor of the `androidx` version in `androidx.compose.foundation`, accompanist/insets won't be getting an update to fix this issue as the upstream version will be the focus of ongoing work.

If a similar issue occurs with just the underlying inset APIs, then that would likely be a platform issue or an `androidx.core` issue.

Otherwise, if the same issue is present with the new `androidx.compose.foundation` APIs please open an upstream issue there. Thanks!

**Comment by alexvanyo** [comment]
For posterity and if this issue shows up in searches, this is the upstream issue:
https://issuetracker.google.com/issues/229861834
